server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.1.201:3306/flowable-test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  database-schema-update: true

